/*===================================================
CUSTOMER PURCHESE BEHAVIOR ANALYSIS
TOOL; SQL
DATASET CUSTOMERS TABLE
=====================================================*/

-- Exploring our dataset
USE customer_behaviors;

SELECT *
FROM customers;

-- Business Questions

===========================================================================================
-- Q1. What is the total revenue generated by male customers compared to female customers?
===========================================================================================
SELECT 
            gender,
        SUM(purchase_amount) AS total_customers
FROM customers
GROUP BY gender;


========================================================================================================
-- Q2. Which customers used a discount but still spent more than the company’s average purchase amount?
========================================================================================================
SELECT customer_id, purchase_amount
FROM customers
WHERE discount_applied ='YES'
AND purchase_amount > 
(
SELECT AVG(purchase_amount)
FROM customers
);



==================================================================================
-- Q3. Which five products have the highest average customer review ratings?
===================================================================================
SELECT item_purchased,
		ROUND(AVG(review_rating),1) AS 'product Rating'
        FROM customers
        GROUP BY item_purchased
        ORDER BY AVG(review_rating) DESC
        LIMIT 5;
        


===================================================================================================================================        
-- Q4. How does the average purchase amount compare between customers using Standard shipping and those using Express shipping?
=================================================================================================================================
SELECT  shipping_type,
ROUND(AVG(purchase_amount),1) AS AVG_PURCHASE_AMOUNT
FROM customers
WHERE shipping_type IN ('standard','Express')
GROUP BY shipping_type;




============================================================================================================================================
-- Q5. Do subscribed customers spend more than non-subscribed customers in terms of both average spending and total revenue contribution?
============================================================================================================================================
SELECT subscription_status,
      AVG(purchase_amount) AS avg_spent,
      SUM(purchase_amount) AS total_revenue
FROM customers
	GROUP BY subscription_status;
    



===================================================================================================    
-- Q6. Which five products have the highest percentage of purchases made with discounts applied?
===================================================================================================
SELECT item_purchased,
       SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END) 
       / COUNT(*) *100 AS discount_rate
FROM customers
GROUP BY item_purchased 
ORDER BY discount_rate DESC
LIMIT 5;



=====================================================================================================================================================
-- Q7. How can customers be segmented into New, Returning, and Loyal groups based on their previous purchases, and what is the size of each segment?
======================================================================================================================================================
WITH customer_type AS (
SELECT customer_id, previous_purchases,	
	CASE 
		WHEN previous_purchases =1 THEN 'NEW'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
	END AS customer_segment
    FROM customers
    )
    SELECT customer_segment, COUNT(*) AS total_customers
    FROM customer_type
    GROUP BY customer_segment;




=====================================================================================
-- Q8. What are the top three most purchased products within each product category?
=====================================================================================
WITH product_ranks AS 
( 
SELECT category,item_purchased,
	RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS item_Rank
FROM customers
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased
FROM product_ranks
WHERE item_rank >=3;




==============================================================================================================
-- Q9. Are customers who are repeat buyers (more than five previous purchases) more likely to be subscribed?
===============================================================================================================
 
    SELECT
        CASE 
            WHEN previous_purchases > 5 THEN 'Repeat Buyer'
            ELSE 'Non-Repeat Buyer'
			END AS Buyer_Type,
		subscription_status,
        COUNT(*) AS Total_customers
        FROM customers
        GROUP BY Buyer_Type, subscription_status; 




=======================================================================================
-- Q10. How does total revenue contribution vary across different customer age groups?
========================================================================================
SELECT 
	age_group,
    SUM(purchase_amount) AS total_revenue
    FROM customers
    GROUP BY age_group
    ORDER BY  total_revenue DESC;